name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: |
          pip install --upgrade platformio
          pio pkg install -g -p https://github.com/Community-PIO-CH32V/platform-ch32v.git

      - name: Build PlatformIO Project
        run: pio run

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            .pio/build/genericCH582F/firmware.bin

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            .pio/build/genericCH582F/firmware.bin
          overwrite: true
